set_property SRC_FILE_INFO {cfile:C:/ZYBO/demo/demo.srcs/constrs_1/new/demo.xdc rfile:../../../demo.srcs/constrs_1/new/demo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports a]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports b]
